steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.open-sna-worker
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  machineType: E2_HIGHCPU_8
  diskSizeGb: 100
timeout: 7200s
