import type { Locale } from "@/lib/i18n";
import {
  ACADEMY_LEVELS,
  ACADEMY_TRACKS,
  type AcademyLessonRecord,
  type LocalizedAcademyLesson,
} from "@/lib/academy-types";

export const academyLessons: AcademyLessonRecord[] = [
  {
    id: "academy-006",
    sequence: 6,
    slug: "model-tie-formation-with-ergms",
    track: "responsible-application",
    level: "advanced",
    analysisApproach: "social-network-analysis",
    publishedAt: "2026-08-09",
    reviewedAt: "2026-08-09",
    durationMinutes: 16,
    sources: [
      {
        label: "Robins and colleagues: An introduction to exponential random graph models",
        url: "https://doi.org/10.1016/j.socnet.2006.08.002",
      },
      {
        label: "Hunter and colleagues: The ergm package",
        url: "https://doi.org/10.18637/jss.v024.i03",
      },
    ],
    localizations: {
      en: {
        title: "Model Tie Formation with Exponential Random Graph Models",
        shortSummary:
          "Build an ERGM that compares the observed network with plausible alternatives while representing density, reciprocity, closure, and actor attributes explicitly.",
        tags: ["ERGM", "tie formation", "goodness of fit"],
        visualLabel: "ERGM",
        learningObjectives: [
          "Express a network hypothesis as a set of interpretable ERGM terms.",
          "Separate endogenous network structure from actor or dyadic covariates.",
          "Use convergence, simulation, and goodness-of-fit checks before interpreting parameters.",
        ],
        scenario:
          "A school wants to understand whether a mentoring network reflects simple opportunity, reciprocal choice, triadic closure, or similarity in teaching experience. The observed network is treated as one realization among many networks that could have formed on the same set of educators.",
        nodes: "Educators participating in one bounded mentoring program.",
        ties: "A directed tie records that educator A regularly seeks instructional advice from educator B.",
        networkType:
          "One-mode, directed, binary network with educator attributes and a dyadic same-department indicator.",
        tutorialSteps: [
          {
            title: "Define the reference process",
            action:
              "Begin with an edges term so every additional effect is interpreted relative to the baseline prevalence of ties. State the node set, which dyads were possible, and whether missing nominations mean no tie or missing data.",
            checkpoint:
              "You can explain what a network generated by the baseline model would look like and which ties were eligible to occur.",
          },
          {
            title: "Add theory-driven terms",
            action:
              "Represent reciprocity with a mutual term, local closure with an appropriate shared-partner term, and actor or dyadic hypotheses with covariates. Add terms because they answer a research question, not because they improve significance.",
            checkpoint:
              "Every term has a written hypothesis, a direction you expect, and a clear distinction between structure and attributes.",
          },
          {
            title: "Fit and diagnose the model",
            action:
              "Inspect MCMC diagnostics, parameter stability, warnings, and signs of degeneracy. Simulate networks from the fitted model and compare statistics that were fitted as well as meaningful statistics that were not included directly.",
            checkpoint:
              "Simulated networks are plausible for the study setting and do not collapse into nearly empty or complete graphs.",
          },
          {
            title: "Interpret conditional associations",
            action:
              "Translate coefficients into conditional changes in the log odds of a tie while holding the rest of the network fixed. Report uncertainty, specification choices, goodness of fit, and sensitivity to alternative terms.",
            checkpoint:
              "Your conclusion describes modeled association in a bounded network and does not claim that an ERGM alone identified a causal mechanism.",
          },
        ],
        interpretation: [
          "A positive reciprocity parameter means mutual ties occur more often than expected under the rest of the fitted model. A positive closure term means two actors with shared partners have greater conditional propensity to connect, given the included structure and covariates. The meaning is always conditional on the full specification.",
          "Parameter signs are not enough. A useful ERGM must converge, generate credible networks, and reproduce important features not forced directly by the model. Competing specifications may support different interpretations, so the final account should document the model-building path and rejected alternatives.",
        ],
        coreIdeas: [
          "An ERGM defines a probability distribution over networks on a fixed node set.",
          "Terms represent proposed structural and attribute-based contributions to tie probability.",
          "Simulation and goodness of fit are part of inference, not optional decoration.",
        ],
        practiceTask:
          "Write a four-term ERGM specification for a classroom advice network using edges, reciprocity, closure, and one experience-similarity term. For each term, state the hypothesis and one diagnostic you would inspect.",
        responsibleUse:
          "Do not turn fitted propensities into labels about individual educators. Small bounded networks can be identifiable even after names are removed. Limit access to raw ties, report uncertainty and model dependence, and avoid intervention decisions based on one fitted network.",
        relatedConcepts: ["MCMC diagnostics", "triadic closure", "model degeneracy"],
      },
      "zh-hant": {
        title: "運用指數隨機圖模型分析連結形成",
        shortSummary:
          "建立 ERGM，把觀察到的網絡與合理的替代網絡比較，並清楚呈現密度、互惠、閉合及行動者屬性的作用。",
        tags: ["ERGM", "連結形成", "擬合優度"],
        visualLabel: "ERGM",
        learningObjectives: [
          "把網絡假設轉化為可詮釋的 ERGM 項。",
          "區分內生網絡結構與行動者或二元關係共變量。",
          "在詮釋參數前檢查收斂、模擬及擬合優度。",
        ],
        scenario:
          "一所學校希望了解導師網絡是反映接觸機會、互惠選擇、三元閉合，還是教學年資相似性。分析把觀察到的網絡視為同一組教師之間許多可能網絡中的一個實現。",
        nodes: "參與同一個有清楚邊界之導師計劃的教師。",
        ties: "有向連結表示教師 A 定期向教師 B 尋求教學建議。",
        networkType: "單模式、有向、二元網絡，包含教師屬性及是否同一部門的二元指標。",
        tutorialSteps: [
          {
            title: "界定參考過程",
            action:
              "先加入 edges 項，讓其餘效應都相對於基本連結比例來詮釋。說明節點集合、哪些二元關係可能發生，以及沒有提名代表無連結還是缺失資料。",
            checkpoint: "你能說明基準模型生成的網絡會有甚麼特徵，以及哪些連結有可能出現。",
          },
          {
            title: "加入理論驅動的模型項",
            action:
              "以 mutual 項表示互惠，以合適的共享夥伴項表示局部閉合，再以共變量表示行動者或二元關係假設。每個模型項都應回答研究問題，而不是只為取得顯著結果。",
            checkpoint: "每個模型項都有書面假設、預期方向，並清楚區分結構與屬性。",
          },
          {
            title: "擬合並診斷模型",
            action:
              "檢視 MCMC 診斷、參數穩定性、警告及退化跡象。從擬合模型模擬網絡，並比較模型直接包含及沒有直接包含但具實質意義的統計量。",
            checkpoint: "模擬網絡符合研究情境，不會幾乎全部為空或全部連結。",
          },
          {
            title: "詮釋條件關聯",
            action:
              "把係數解釋為在網絡其餘部分固定時，某條連結對數勝算的條件變化。報告不確定性、模型設定、擬合優度及替代模型項的敏感度。",
            checkpoint: "結論只描述有邊界網絡內的模型關聯，不會聲稱 ERGM 本身已識別因果機制。",
          },
        ],
        interpretation: [
          "正向互惠參數表示，在控制模型其他部分後，雙向連結比預期更常出現。正向閉合項表示在其他條件相同時，共有夥伴的兩位行動者較容易建立連結。任何參數都必須放在完整模型設定中理解。",
          "參數正負並不足夠。可用的 ERGM 必須收斂、生成可信網絡，並重現沒有被模型直接強制的關鍵特徵。不同設定可能支持不同詮釋，因此需要記錄模型建立過程及被拒絕的替代方案。",
        ],
        coreIdeas: [
          "ERGM 為固定節點集合上的可能網絡建立機率分布。",
          "模型項表示網絡結構及屬性對連結機率的可能貢獻。",
          "模擬與擬合優度是推論的一部分，而不是可有可無的裝飾。",
        ],
        practiceTask:
          "為課堂建議網絡寫出包含 edges、互惠、閉合及一個年資相似項的四項 ERGM。為每一項寫出假設及一項需要檢查的診斷。",
        responsibleUse:
          "不要把擬合的連結傾向轉化為對個別教師的標籤。小型有邊界網絡即使移除姓名仍可能被識別。應限制原始連結資料的存取、報告不確定性與模型依賴性，並避免根據單一網絡模型作出介入決定。",
        relatedConcepts: ["MCMC 診斷", "三元閉合", "模型退化"],
      },
      "zh-hans": {
        title: "运用指数随机图模型分析连接形成",
        shortSummary:
          "建立 ERGM，把观察到的网络与合理的替代网络比较，并清楚呈现密度、互惠、闭合及行动者属性的作用。",
        tags: ["ERGM", "连接形成", "拟合优度"],
        visualLabel: "ERGM",
        learningObjectives: [
          "把网络假设转化为可解释的 ERGM 项。",
          "区分内生网络结构与行动者或二元关系协变量。",
          "在解释参数前检查收敛、模拟及拟合优度。",
        ],
        scenario:
          "一所学校希望了解导师网络是反映接触机会、互惠选择、三元闭合，还是教学年资相似性。分析把观察到的网络视为同一组教师之间许多可能网络中的一个实现。",
        nodes: "参与同一个有清楚边界之导师计划的教师。",
        ties: "有向连接表示教师 A 定期向教师 B 寻求教学建议。",
        networkType: "单模式、有向、二元网络，包含教师属性及是否同一部门的二元指标。",
        tutorialSteps: [
          {
            title: "界定参考过程",
            action:
              "先加入 edges 项，让其余效应都相对于基本连接比例来解释。说明节点集合、哪些二元关系可能发生，以及没有提名代表无连接还是缺失数据。",
            checkpoint: "你能说明基准模型生成的网络会有什么特征，以及哪些连接有可能出现。",
          },
          {
            title: "加入理论驱动的模型项",
            action:
              "以 mutual 项表示互惠，以合适的共享伙伴项表示局部闭合，再以协变量表示行动者或二元关系假设。每个模型项都应回答研究问题，而不是只为取得显著结果。",
            checkpoint: "每个模型项都有书面假设、预期方向，并清楚区分结构与属性。",
          },
          {
            title: "拟合并诊断模型",
            action:
              "检视 MCMC 诊断、参数稳定性、警告及退化迹象。从拟合模型模拟网络，并比较模型直接包含及没有直接包含但具实质意义的统计量。",
            checkpoint: "模拟网络符合研究情境，不会几乎全部为空或全部连接。",
          },
          {
            title: "解释条件关联",
            action:
              "把系数解释为在网络其余部分固定时，某条连接对数优势的条件变化。报告不确定性、模型设定、拟合优度及替代模型项的敏感度。",
            checkpoint: "结论只描述有边界网络内的模型关联，不会声称 ERGM 本身已识别因果机制。",
          },
        ],
        interpretation: [
          "正向互惠参数表示，在控制模型其他部分后，双向连接比预期更常出现。正向闭合项表示在其他条件相同时，共有伙伴的两位行动者较容易建立连接。任何参数都必须放在完整模型设定中理解。",
          "参数正负并不足够。可用的 ERGM 必须收敛、生成可信网络，并重现没有被模型直接强制的关键特征。不同设定可能支持不同解释，因此需要记录模型建立过程及被拒绝的替代方案。",
        ],
        coreIdeas: [
          "ERGM 为固定节点集合上的可能网络建立概率分布。",
          "模型项表示网络结构及属性对连接概率的可能贡献。",
          "模拟与拟合优度是推断的一部分，而不是可有可无的装饰。",
        ],
        practiceTask:
          "为课堂建议网络写出包含 edges、互惠、闭合及一个年资相似项的四项 ERGM。为每一项写出假设及一项需要检查的诊断。",
        responsibleUse:
          "不要把拟合的连接倾向转化为对个别教师的标签。小型有边界网络即使移除姓名仍可能被识别。应限制原始连接数据的访问、报告不确定性与模型依赖性，并避免根据单一网络模型作出干预决定。",
        relatedConcepts: ["MCMC 诊断", "三元闭合", "模型退化"],
      },
    },
  },
  {
    id: "academy-005",
    sequence: 5,
    slug: "test-dyadic-associations-with-qap",
    track: "responsible-application",
    level: "advanced",
    analysisApproach: "social-network-analysis",
    publishedAt: "2026-08-09",
    reviewedAt: "2026-08-09",
    durationMinutes: 14,
    sources: [
      {
        label: "Krackhardt: Predicting with networks using QAP",
        url: "https://doi.org/10.1016/0378-8733(88)90004-4",
      },
      {
        label: "Butts: Social Network Analysis with sna",
        url: "https://doi.org/10.18637/jss.v024.i06",
      },
    ],
    localizations: {
      en: {
        title: "Test Dyadic Associations with QAP",
        shortSummary:
          "Use label permutations to compare aligned relationship matrices while respecting the dependence created when many dyads share the same actors.",
        tags: ["QAP", "dyadic data", "permutation test"],
        visualLabel: "QAP",
        learningObjectives: [
          "Recognize why ordinary independent-observation tests are unsafe for dyadic matrices.",
          "Align outcome and predictor matrices on the same actors and direction.",
          "Interpret a QAP coefficient, permutation distribution, and evidence boundary together.",
        ],
        scenario:
          "A project team asks whether students who exchange study advice also collaborate on assignments. Both relations involve the same class, so dyads that share a student are not independent observations.",
        nodes: "Students who were eligible to report both advice and collaboration ties.",
        ties: "Two aligned directed matrices record advice seeking and assignment collaboration between the same ordered pairs.",
        networkType:
          "Two one-mode, directed, binary networks on an identical, consistently ordered node set.",
        tutorialSteps: [
          {
            title: "Align the matrices",
            action:
              "Create one row and column order for the shared actor set, then reorder every matrix to match it. Decide how to treat diagonals, missing dyads, direction, and any actors present in only one source.",
            checkpoint:
              "The same cell in every matrix refers to the same ordered pair, and missingness is never silently converted to zero.",
          },
          {
            title: "State the dyadic hypothesis",
            action:
              "Specify the outcome matrix, predictor matrix, expected direction, and covariate matrices before analysis. A simple example asks whether advice ties are more likely where collaboration ties exist.",
            checkpoint:
              "The hypothesis names the relation being explained and distinguishes it from actor attributes or network controls.",
          },
          {
            title: "Permute actor labels",
            action:
              "Calculate the observed correlation or regression coefficient, then repeatedly permute rows and matching columns together. This preserves each permuted network's internal structure while breaking its alignment with the other matrix.",
            checkpoint:
              "Rows and columns move as a pair, the number of permutations is documented, and a random seed supports reproduction.",
          },
          {
            title: "Report effect and uncertainty",
            action:
              "Compare the observed statistic with the permutation distribution. Report the coefficient, permutation-based probability, matrix definitions, controls, permutation count, and sensitivity to direction or missing-data choices.",
            checkpoint:
              "The write-up treats QAP as evidence of dyadic association, not proof that one relationship caused the other.",
          },
        ],
        interpretation: [
          "A positive observed coefficient means aligned dyads with stronger or present predictor ties tend to have stronger or present outcome ties. The permutation result asks how unusual that alignment is when actor labels are reassigned while network structure is retained.",
          "QAP addresses a specific dependence problem, but it does not repair weak measurement, omitted relational processes, temporal ambiguity, or a mismatched boundary. Results can change when matrices use different time windows, tie definitions, or missing-data rules.",
        ],
        coreIdeas: [
          "Dyads sharing actors violate the independence assumed by ordinary tests.",
          "QAP permutes actor labels by moving corresponding rows and columns together.",
          "A permutation result supports association under a stated null model, not causation.",
        ],
        practiceTask:
          "Sketch two 5 by 5 matrices for advice and collaboration. Mark one permutation that moves the same row and column labels together, then explain what remains preserved and what is deliberately broken.",
        responsibleUse:
          "Relational matrices may expose who is isolated, avoided, or heavily relied upon. Use pseudonymous identifiers, restrict raw matrix access, suppress recognizable examples, and avoid presenting a significant association as a judgment about any individual learner.",
        relatedConcepts: ["MRQAP", "matrix alignment", "permutation null model"],
      },
      "zh-hant": {
        title: "運用 QAP 檢驗二元關係關聯",
        shortSummary:
          "運用標籤置換比較對齊的關係矩陣，同時處理多個二元關係共享相同行動者所產生的相依性。",
        tags: ["QAP", "二元關係資料", "置換檢驗"],
        visualLabel: "QAP",
        learningObjectives: [
          "辨識為何假設觀察值獨立的一般檢驗不適合二元關係矩陣。",
          "把結果矩陣與預測矩陣依相同行動者及方向對齊。",
          "同時詮釋 QAP 係數、置換分布及證據界線。",
        ],
        scenario:
          "研究團隊希望了解互相交換學習建議的學生是否也會合作完成作業。兩種關係都來自同一班級，因此共享同一學生的二元關係並非獨立觀察值。",
        nodes: "有資格報告建議及合作連結的學生。",
        ties: "兩個對齊的有向矩陣，記錄相同有序學生配對之間的尋求建議及作業合作。",
        networkType: "兩個採用完全相同且順序一致之節點集合的單模式、有向、二元網絡。",
        tutorialSteps: [
          {
            title: "對齊矩陣",
            action:
              "為共享的行動者集合建立統一行列次序，並把所有矩陣重新排序。先決定如何處理對角線、缺失二元關係、方向，以及只在一個資料來源出現的行動者。",
            checkpoint: "所有矩陣的同一儲存格都代表同一個有序配對，而且缺失值不會被默認轉成零。",
          },
          {
            title: "說明二元關係假設",
            action:
              "在分析前指定結果矩陣、預測矩陣、預期方向及共變量矩陣。例如，可詢問有合作連結的學生之間是否更可能存在建議連結。",
            checkpoint: "假設清楚指出要解釋的關係，並把它與行動者屬性或網絡控制項區分。",
          },
          {
            title: "置換行動者標籤",
            action:
              "先計算觀察到的相關或迴歸係數，再重複同步置換對應行與列。這會保留每個置換網絡的內部結構，同時打破兩個矩陣之間原有的對齊。",
            checkpoint: "行列成對移動，清楚記錄置換次數，並設定隨機種子以便重現。",
          },
          {
            title: "報告效應與不確定性",
            action:
              "把觀察統計量與置換分布比較。報告係數、置換機率、矩陣定義、控制項、置換次數，以及對方向或缺失資料處理的敏感度。",
            checkpoint: "報告把 QAP 視為二元關係關聯證據，而不是一種關係導致另一種關係的證明。",
          },
        ],
        interpretation: [
          "正向觀察係數表示，在對齊的二元關係中，較強或存在的預測連結傾向對應較強或存在的結果連結。置換結果檢查當行動者標籤被重新分配而網絡結構獲保留時，原有對齊有多不尋常。",
          "QAP 處理的是特定相依性問題，但不能修補薄弱量度、遺漏的關係過程、時間次序不清或邊界不一致。不同時間窗口、連結定義及缺失資料規則都可能改變結果。",
        ],
        coreIdeas: [
          "共享行動者的二元關係違反一般檢驗的獨立性假設。",
          "QAP 透過同步移動相應行列來置換行動者標籤。",
          "置換結果只支持特定虛無模型下的關聯，而非因果關係。",
        ],
        practiceTask:
          "為建議及合作畫出兩個 5 乘 5 矩陣。標示一次同步移動相同行列標籤的置換，並解釋哪些結構被保留、哪些對齊被刻意打破。",
        responsibleUse:
          "關係矩陣可能暴露誰被孤立、被避開或被高度依賴。應使用化名識別碼、限制原始矩陣存取、隱去可辨識例子，並避免把顯著關聯當成對個別學生的判斷。",
        relatedConcepts: ["MRQAP", "矩陣對齊", "置換虛無模型"],
      },
      "zh-hans": {
        title: "运用 QAP 检验二元关系关联",
        shortSummary:
          "运用标签置换比较对齐的关系矩阵，同时处理多个二元关系共享相同行动者所产生的依赖性。",
        tags: ["QAP", "二元关系数据", "置换检验"],
        visualLabel: "QAP",
        learningObjectives: [
          "识别为何假设观察值独立的一般检验不适合二元关系矩阵。",
          "把结果矩阵与预测矩阵按相同行动者及方向对齐。",
          "同时解释 QAP 系数、置换分布及证据边界。",
        ],
        scenario:
          "研究团队希望了解互相交换学习建议的学生是否也会合作完成作业。两种关系都来自同一班级，因此共享同一学生的二元关系并非独立观察值。",
        nodes: "有资格报告建议及合作连接的学生。",
        ties: "两个对齐的有向矩阵，记录相同有序学生配对之间的寻求建议及作业合作。",
        networkType: "两个采用完全相同且顺序一致之节点集合的单模式、有向、二元网络。",
        tutorialSteps: [
          {
            title: "对齐矩阵",
            action:
              "为共享的行动者集合建立统一行列次序，并把所有矩阵重新排序。先决定如何处理对角线、缺失二元关系、方向，以及只在一个数据来源出现的行动者。",
            checkpoint: "所有矩阵的同一单元格都代表同一个有序配对，而且缺失值不会被默认转成零。",
          },
          {
            title: "说明二元关系假设",
            action:
              "在分析前指定结果矩阵、预测矩阵、预期方向及协变量矩阵。例如，可询问有合作连接的学生之间是否更可能存在建议连接。",
            checkpoint: "假设清楚指出要解释的关系，并把它与行动者属性或网络控制项区分。",
          },
          {
            title: "置换行动者标签",
            action:
              "先计算观察到的相关或回归系数，再重复同步置换对应行与列。这会保留每个置换网络的内部结构，同时打破两个矩阵之间原有的对齐。",
            checkpoint: "行列成对移动，清楚记录置换次数，并设置随机种子以便重现。",
          },
          {
            title: "报告效应与不确定性",
            action:
              "把观察统计量与置换分布比较。报告系数、置换概率、矩阵定义、控制项、置换次数，以及对方向或缺失数据处理的敏感度。",
            checkpoint: "报告把 QAP 视为二元关系关联证据，而不是一种关系导致另一种关系的证明。",
          },
        ],
        interpretation: [
          "正向观察系数表示，在对齐的二元关系中，较强或存在的预测连接倾向对应较强或存在的结果连接。置换结果检查当行动者标签被重新分配而网络结构获保留时，原有对齐有多不寻常。",
          "QAP 处理的是特定依赖性问题，但不能修补薄弱测量、遗漏的关系过程、时间次序不清或边界不一致。不同时间窗口、连接定义及缺失数据规则都可能改变结果。",
        ],
        coreIdeas: [
          "共享行动者的二元关系违反一般检验的独立性假设。",
          "QAP 通过同步移动相应行列来置换行动者标签。",
          "置换结果只支持特定零假设模型下的关联，而非因果关系。",
        ],
        practiceTask:
          "为建议及合作画出两个 5 乘 5 矩阵。标示一次同步移动相同行列标签的置换，并解释哪些结构被保留、哪些对齐被刻意打破。",
        responsibleUse:
          "关系矩阵可能暴露谁被孤立、被避开或被高度依赖。应使用化名标识符、限制原始矩阵访问、隐去可识别例子，并避免把显著关联当成对个别学生的判断。",
        relatedConcepts: ["MRQAP", "矩阵对齐", "置换零假设模型"],
      },
    },
  },
  {
    id: "academy-004",
    sequence: 4,
    slug: "examine-cohesion-components-and-communities",
    track: "network-theory",
    level: "applied",
    analysisApproach: "social-network-analysis",
    publishedAt: "2026-08-09",
    reviewedAt: "2026-08-09",
    durationMinutes: 12,
    sources: [
      {
        label: "Newman and Girvan: Finding and evaluating community structure",
        url: "https://doi.org/10.1103/PhysRevE.69.026113",
      },
      {
        label: "Moody and White: Structural cohesion and embeddedness",
        url: "https://doi.org/10.2307/3088904",
      },
    ],
    localizations: {
      en: {
        title: "Examine Cohesion, Components, and Communities",
        shortSummary:
          "Move from one network picture to a defensible account of reachability, density, reciprocity, structural cohesion, and possible community divisions.",
        tags: ["cohesion", "components", "communities"],
        visualLabel: "COHESION",
        learningObjectives: [
          "Distinguish whole-network density from reachability and component structure.",
          "Use reciprocity and cohesive-subgroup measures only when they match the tie definition.",
          "Treat community partitions as model-dependent summaries rather than natural labels.",
        ],
        scenario:
          "A professional learning network appears to contain several clusters. Leaders want to know whether knowledge can travel across the whole group, where fragile bridges sit, and whether a community algorithm reveals meaningful working groups.",
        nodes: "Teachers in one cross-school professional learning program.",
        ties: "A directed tie records at least one substantive exchange of teaching resources during the term.",
        networkType: "One-mode, directed, weighted network with exchange counts and school membership attributes.",
        tutorialSteps: [
          {
            title: "Check reachability first",
            action:
              "Identify weak and strong components before summarizing the whole network. In a directed network, weak reachability ignores arrow direction while strong reachability requires a directed path both ways.",
            checkpoint:
              "You can state how many actors are outside the main component and whether direction changes the reachability conclusion.",
          },
          {
            title: "Measure density and reciprocity",
            action:
              "Calculate density using the correct denominator for a directed network and calculate reciprocity only for ties where mutual exchange is meaningful. Compare results with a thresholded binary version if the original network is weighted.",
            checkpoint:
              "The denominator, loop rule, direction, weight treatment, and observation window are written beside every reported value.",
          },
          {
            title: "Inspect cohesive structure",
            action:
              "Look for articulation points, bridges, or node-connectivity patterns that reveal how easily a group separates. Use these diagnostics to describe structural vulnerability rather than to label people as problems.",
            checkpoint:
              "Any claimed bridge or cohesive subgroup is checked against the actual paths and the substantive meaning of the tie.",
          },
          {
            title: "Compare community partitions",
            action:
              "Run a documented community method on an appropriate undirected or directed representation, then vary resolution, threshold, or random seed. Compare partitions with known context without forcing school labels to validate the algorithm.",
            checkpoint:
              "The report names the algorithm and settings, shows stability checks, and uses community membership as an analytical summary rather than a fixed identity.",
          },
        ],
        interpretation: [
          "A dense network has many observed ties relative to possible ties, but density does not guarantee that every actor can reach every other actor or that exchange is equitable. Components reveal reachability, while connectivity and bridge diagnostics reveal how robust that reachability is to the loss of particular nodes or ties.",
          "Community detection optimizes a chosen criterion and may return different divisions under different methods or settings. A partition is most useful when it is stable enough to inspect, substantively interpretable, and reported alongside cross-community ties that prevent the visualization from exaggerating separation.",
        ],
        coreIdeas: [
          "Density, reachability, reciprocity, cohesion, and community structure answer different questions.",
          "Direction, weights, thresholds, and observation windows can change the apparent subgroup structure.",
          "Communities are analytical partitions, not automatically real or permanent social groups.",
        ],
        practiceTask:
          "Draw a network with two dense clusters joined by one bridge. Report its components, identify the vulnerable connection, then explain how removing direction or changing one tie could alter the conclusion.",
        responsibleUse:
          "Cluster labels can harden into reputational categories. Do not publish identifiable subgroup maps without a clear purpose and consent. Discuss alternative partitions, uncertainty, and cross-group relationships, and never equate structural separation with motivation, ability, or intent.",
        relatedConcepts: ["density", "structural cohesion", "modularity"],
      },
      "zh-hant": {
        title: "檢視凝聚力、連通分量與社群",
        shortSummary:
          "由一幅網絡圖進一步建立可辯護的分析，說明可達性、密度、互惠、結構凝聚力及可能的社群分界。",
        tags: ["凝聚力", "連通分量", "社群"],
        visualLabel: "凝聚力",
        learningObjectives: [
          "區分整體網絡密度、可達性及連通分量結構。",
          "只在符合連結定義時使用互惠及凝聚子群指標。",
          "把社群分割視為依賴模型的摘要，而不是自然形成的標籤。",
        ],
        scenario:
          "一個專業學習網絡似乎包含多個群組。領導者希望了解知識能否在整個群體流動、脆弱橋樑位於何處，以及社群演算法能否揭示有意義的工作小組。",
        nodes: "參與同一跨校專業學習計劃的教師。",
        ties: "有向連結表示學期內至少一次實質教學資源交流。",
        networkType: "單模式、有向、加權網絡，包含交流次數及學校成員屬性。",
        tutorialSteps: [
          {
            title: "先檢查可達性",
            action:
              "在概括整體網絡前先辨識弱連通及強連通分量。在有向網絡中，弱可達性忽略箭嘴方向，強可達性則要求雙方都存在有向路徑。",
            checkpoint: "你能說明主連通分量外有多少行動者，以及方向是否改變可達性結論。",
          },
          {
            title: "量度密度與互惠",
            action:
              "使用有向網絡的正確分母計算密度，並只在互相交流具意義時計算互惠。若原網絡有權重，可與設定門檻後的二元版本比較。",
            checkpoint: "每個數值旁都記錄分母、自連結規則、方向、權重處理及觀察時段。",
          },
          {
            title: "檢視凝聚結構",
            action:
              "尋找割點、橋或節點連通性模式，以了解群體有多容易分裂。這些診斷用來描述結構脆弱性，而不是把某些人標籤為問題。",
            checkpoint: "所有橋樑或凝聚子群判斷都與實際路徑及連結的實質意義核對。",
          },
          {
            title: "比較社群分割",
            action:
              "在合適的有向或無向表示上執行有清楚記錄的社群方法，再改變解析度、門檻或隨機種子。把分割與已知情境比較，但不要強迫學校標籤去驗證演算法。",
            checkpoint: "報告列出演算法及設定、展示穩定性檢查，並把社群成員身分視為分析摘要而非固定身分。",
          },
        ],
        interpretation: [
          "高密度網絡相對於可能連結擁有較多實際連結，但不保證所有人都能互相到達，也不代表交流公平。連通分量呈現可達性，而連通性及橋樑診斷則呈現失去特定節點或連結後的穩健程度。",
          "社群偵測會最佳化某個選定準則，不同方法或設定可能產生不同分界。只有當分割具一定穩定性、能依情境解釋，並同時呈現跨社群連結時，它才是有用的分析摘要。",
        ],
        coreIdeas: [
          "密度、可達性、互惠、凝聚力與社群結構回答不同問題。",
          "方向、權重、門檻及觀察時段都可能改變表面的子群結構。",
          "社群是分析分割，不必然是真實或永久的社會群體。",
        ],
        practiceTask:
          "畫出兩個高密度群組由一條橋連接的網絡。報告連通分量及脆弱連結，再解釋移除方向或改變一條連結會如何影響結論。",
        responsibleUse:
          "群組標籤可能固化成聲譽分類。沒有清楚目的與同意時，不應公開可識別的子群圖。應討論替代分割、不確定性及跨群關係，並切勿把結構分離等同於動機、能力或意圖。",
        relatedConcepts: ["密度", "結構凝聚力", "模組度"],
      },
      "zh-hans": {
        title: "检视凝聚力、连通分量与社群",
        shortSummary:
          "由一幅网络图进一步建立可辩护的分析，说明可达性、密度、互惠、结构凝聚力及可能的社群分界。",
        tags: ["凝聚力", "连通分量", "社群"],
        visualLabel: "凝聚力",
        learningObjectives: [
          "区分整体网络密度、可达性及连通分量结构。",
          "只在符合连接定义时使用互惠及凝聚子群指标。",
          "把社群分割视为依赖模型的摘要，而不是自然形成的标签。",
        ],
        scenario:
          "一个专业学习网络似乎包含多个群组。领导者希望了解知识能否在整个群体流动、脆弱桥梁位于何处，以及社群算法能否揭示有意义的工作小组。",
        nodes: "参与同一跨校专业学习计划的教师。",
        ties: "有向连接表示学期内至少一次实质教学资源交流。",
        networkType: "单模式、有向、加权网络，包含交流次数及学校成员属性。",
        tutorialSteps: [
          {
            title: "先检查可达性",
            action:
              "在概括整体网络前先识别弱连通及强连通分量。在有向网络中，弱可达性忽略箭头方向，强可达性则要求双方都存在有向路径。",
            checkpoint: "你能说明主连通分量外有多少行动者，以及方向是否改变可达性结论。",
          },
          {
            title: "测量密度与互惠",
            action:
              "使用有向网络的正确分母计算密度，并只在互相交流具意义时计算互惠。若原网络有权重，可与设置阈值后的二元版本比较。",
            checkpoint: "每个数值旁都记录分母、自连接规则、方向、权重处理及观察时段。",
          },
          {
            title: "检视凝聚结构",
            action:
              "寻找割点、桥或节点连通性模式，以了解群体有多容易分裂。这些诊断用来描述结构脆弱性，而不是把某些人标记为问题。",
            checkpoint: "所有桥梁或凝聚子群判断都与实际路径及连接的实质意义核对。",
          },
          {
            title: "比较社群分割",
            action:
              "在合适的有向或无向表示上执行有清楚记录的社群方法，再改变分辨率、阈值或随机种子。把分割与已知情境比较，但不要强迫学校标签去验证算法。",
            checkpoint: "报告列出算法及设定、展示稳定性检查，并把社群成员身份视为分析摘要而非固定身份。",
          },
        ],
        interpretation: [
          "高密度网络相对于可能连接拥有较多实际连接，但不保证所有人都能互相到达，也不代表交流公平。连通分量呈现可达性，而连通性及桥梁诊断则呈现失去特定节点或连接后的稳健程度。",
          "社群检测会优化某个选定标准，不同方法或设定可能产生不同分界。只有当分割具一定稳定性、能按情境解释，并同时呈现跨社群连接时，它才是有用的分析摘要。",
        ],
        coreIdeas: [
          "密度、可达性、互惠、凝聚力与社群结构回答不同问题。",
          "方向、权重、阈值及观察时段都可能改变表面的子群结构。",
          "社群是分析分割，不必然是真实或永久的社会群体。",
        ],
        practiceTask:
          "画出两个高密度群组由一条桥连接的网络。报告连通分量及脆弱连接，再解释移除方向或改变一条连接会如何影响结论。",
        responsibleUse:
          "群组标签可能固化成声誉分类。没有清楚目的与同意时，不应公开可识别的子群图。应讨论替代分割、不确定性及跨群关系，并切勿把结构分离等同于动机、能力或意图。",
        relatedConcepts: ["密度", "结构凝聚力", "模块度"],
      },
    },
  },
  {
    id: "academy-003",
    sequence: 3,
    slug: "interpret-centrality-without-overclaiming",
    track: "methods-visualization",
    level: "applied",
    analysisApproach: "social-network-analysis",
    publishedAt: "2026-08-09",
    reviewedAt: "2026-08-09",
    durationMinutes: 11,
    sources: [
      {
        label: "Freeman: Centrality in social networks",
        url: "https://doi.org/10.1016/0378-8733(78)90021-7",
      },
      {
        label: "Borgatti: Centrality and network flow",
        url: "https://doi.org/10.1016/j.socnet.2004.11.008",
      },
    ],
    localizations: {
      en: {
        title: "Interpret Centrality Without Overclaiming",
        shortSummary:
          "Calculate degree, betweenness, and closeness only after matching each measure to a plausible process of access, brokerage, or reachability.",
        tags: ["centrality", "brokerage", "reachability"],
        visualLabel: "CENTRALITY",
        learningObjectives: [
          "Explain what degree, betweenness, and closeness assume about movement through a network.",
          "Choose direction, weight transformation, and normalization rules before calculation.",
          "Interpret high scores as structural positions rather than personal worth or proven influence.",
        ],
        scenario:
          "A course team wants to identify where peer explanations enter a class discussion network, who connects otherwise separated groups, and who can reach others through short paths. One centrality score cannot answer all three questions.",
        nodes: "Students who participated in a six-week online course discussion.",
        ties: "A directed, weighted tie from A to B counts substantive replies by A to B.",
        networkType: "One-mode, directed, weighted interaction network aggregated across a documented six-week window.",
        tutorialSteps: [
          {
            title: "Name the flow process",
            action:
              "Decide whether the substantive process is direct contact, shortest-path brokerage, rapid reach, diffusion, or something else. Write why network paths are a reasonable representation of that process before selecting a metric.",
            checkpoint: "You can finish the sentence: This centrality is relevant because the process moves through ties by...",
          },
          {
            title: "Prepare direction and weights",
            action:
              "Clarify whether incoming or outgoing degree matters. If higher weights mean stronger or more frequent ties, do not pass them unchanged to a shortest-path function that treats larger values as longer distance. Document any inverse or other transformation.",
            checkpoint: "Arrow direction and weight meaning are consistent with the formula and the research question.",
          },
          {
            title: "Calculate a small measure set",
            action:
              "Compute in-degree and out-degree, betweenness, and a reachability-aware form of closeness. Report raw and normalized values where comparisons across network sizes are intended, and treat disconnected cases explicitly.",
            checkpoint: "No undefined or infinite value is silently replaced, and every normalization rule is recorded.",
          },
          {
            title: "Compare position with context",
            action:
              "Inspect whether high-scoring actors actually perform the process assumed by the measure. Compare rankings across metrics and time windows, and look at the local network around surprising cases before writing conclusions.",
            checkpoint: "The interpretation names the structural opportunity measured and includes at least one alternative explanation for the score.",
          },
        ],
        interpretation: [
          "High degree indicates many observed direct ties under the chosen direction and threshold. High betweenness indicates frequent placement on selected shortest paths, which may suggest brokerage only if the studied resource plausibly follows those paths. High closeness indicates short path distance to reachable others under the chosen definition.",
          "Centrality is conditional on boundary, tie definition, time window, direction, weights, and flow assumptions. A high score does not prove leadership, quality, popularity, or causal influence, and a low score does not prove disengagement. Qualitative and temporal evidence can test whether the structural interpretation fits the setting.",
        ],
        coreIdeas: [
          "Different centralities formalize different kinds of structural opportunity.",
          "Weights and direction must be transformed to match the path logic of the measure.",
          "Centrality ranks positions in a measured network, not human value or causal influence.",
        ],
        practiceTask:
          "For a five-node directed network, identify one node with high in-degree and a different node with high betweenness. Explain what each score could mean for advice exchange and one reason the interpretation might fail.",
        responsibleUse:
          "Centrality rankings can become harmful status labels. Share identifiable scores only when necessary, avoid automatic reward or intervention decisions, include uncertainty and boundary sensitivity, and invite participants to explain unobserved roles that the network missed.",
        relatedConcepts: ["in-degree", "betweenness", "harmonic closeness"],
      },
      "zh-hant": {
        title: "避免過度解讀中心性",
        shortSummary:
          "只有在把指標與接觸、橋接或可達性的合理過程配對後，才計算度數、中介及接近中心性。",
        tags: ["中心性", "橋接", "可達性"],
        visualLabel: "中心性",
        learningObjectives: [
          "說明度數、中介及接近中心性對網絡流動的假設。",
          "在計算前選定方向、權重轉換及標準化規則。",
          "把高分詮釋為結構位置，而不是個人價值或已證實的影響力。",
        ],
        scenario:
          "課程團隊希望了解同儕解釋從何處進入討論網絡、誰連接原本分離的群組，以及誰能經短路徑接觸其他人。單一中心性分數不能回答全部問題。",
        nodes: "所有參與完整六週網上課程討論的學生。",
        ties: "由 A 指向 B 的有向加權連結，表示 A 對 B 作出的實質回覆次數。",
        networkType: "單模式、有向、加權互動網絡，按有清楚記錄的六週時段彙總。",
        tutorialSteps: [
          {
            title: "說明流動過程",
            action:
              "先決定研究關注直接接觸、最短路徑橋接、快速到達、擴散或其他過程。在選擇指標前，寫下為何網絡路徑能合理表示該過程。",
            checkpoint: "你能完成這句話：此中心性與研究相關，因為該過程沿連結以以下方式流動。",
          },
          {
            title: "處理方向與權重",
            action:
              "釐清入度或出度何者有意義。若較高權重代表較強或較頻密的連結，不應直接交給把較大數值視為較長距離的最短路徑函數。記錄倒數或其他轉換。",
            checkpoint: "箭嘴方向及權重意義與公式和研究問題一致。",
          },
          {
            title: "計算一組精簡指標",
            action:
              "計算入度、出度、中介中心性及能處理可達性的接近中心性。若要比較不同規模網絡，應同時報告原始及標準化值，並明確處理不連通情況。",
            checkpoint: "沒有未定義或無限值被靜默替換，而且每項標準化規則都有記錄。",
          },
          {
            title: "以情境核對位置",
            action:
              "檢視高分行動者是否真正參與指標所假設的過程。比較不同指標及時段的排名，並在下結論前檢查出乎預期個案的局部網絡。",
            checkpoint: "詮釋清楚指出被量度的結構機會，並包括至少一個替代解釋。",
          },
        ],
        interpretation: [
          "高度數表示在選定方向及門檻下有較多直接連結。高中介表示經常位於所選最短路徑上，但只有當研究資源合理地沿這些路徑流動時才可能代表橋接。高接近表示依所選定義與可達他人的路徑距離較短。",
          "中心性受邊界、連結定義、時段、方向、權重及流動假設限制。高分不證明領導力、質素、受歡迎程度或因果影響，低分也不證明缺乏參與。質性與時間證據可檢查結構詮釋是否符合情境。",
        ],
        coreIdeas: [
          "不同中心性把不同種類的結構機會形式化。",
          "權重與方向必須轉換至符合指標的路徑邏輯。",
          "中心性排列被量度網絡中的位置，而不是人的價值或因果影響。",
        ],
        practiceTask:
          "在一個五節點有向網絡中，找出一個高入度節點及另一個高中介節點。解釋兩個分數對建議交流可能有何意義，以及各自一個可能失效的原因。",
        responsibleUse:
          "中心性排名可能變成有害的地位標籤。只在必要時分享可識別分數，避免自動獎勵或介入決策，呈現不確定性及邊界敏感度，並邀請參與者說明網絡未能觀察的角色。",
        relatedConcepts: ["入度", "中介中心性", "調和接近中心性"],
      },
      "zh-hans": {
        title: "避免过度解读中心性",
        shortSummary:
          "只有在把指标与接触、桥接或可达性的合理过程配对后，才计算度数、中介及接近中心性。",
        tags: ["中心性", "桥接", "可达性"],
        visualLabel: "中心性",
        learningObjectives: [
          "说明度数、中介及接近中心性对网络流动的假设。",
          "在计算前选定方向、权重转换及标准化规则。",
          "把高分解释为结构位置，而不是个人价值或已证实的影响力。",
        ],
        scenario:
          "课程团队希望了解同伴解释从何处进入讨论网络、谁连接原本分离的群组，以及谁能经短路径接触其他人。单一中心性分数不能回答全部问题。",
        nodes: "所有参与完整六周在线课程讨论的学生。",
        ties: "由 A 指向 B 的有向加权连接，表示 A 对 B 作出的实质回复次数。",
        networkType: "单模式、有向、加权互动网络，按有清楚记录的六周时段汇总。",
        tutorialSteps: [
          {
            title: "说明流动过程",
            action:
              "先决定研究关注直接接触、最短路径桥接、快速到达、扩散或其他过程。在选择指标前，写下为何网络路径能合理表示该过程。",
            checkpoint: "你能完成这句话：此中心性与研究相关，因为该过程沿连接以以下方式流动。",
          },
          {
            title: "处理方向与权重",
            action:
              "理清入度或出度何者有意义。若较高权重代表较强或较频繁的连接，不应直接交给把较大数值视为较长距离的最短路径函数。记录倒数或其他转换。",
            checkpoint: "箭头方向及权重意义与公式和研究问题一致。",
          },
          {
            title: "计算一组精简指标",
            action:
              "计算入度、出度、中介中心性及能处理可达性的接近中心性。若要比较不同规模网络，应同时报告原始及标准化值，并明确处理不连通情况。",
            checkpoint: "没有未定义或无限值被静默替换，而且每项标准化规则都有记录。",
          },
          {
            title: "以情境核对位置",
            action:
              "检视高分行动者是否真正参与指标所假设的过程。比较不同指标及时间段的排名，并在下结论前检查出乎预期案例的局部网络。",
            checkpoint: "解释清楚指出被测量的结构机会，并包括至少一个替代解释。",
          },
        ],
        interpretation: [
          "高度数表示在选定方向及阈值下有较多直接连接。高中介表示经常位于所选最短路径上，但只有当研究资源合理地沿这些路径流动时才可能代表桥接。高接近表示按所选定义与可达他人的路径距离较短。",
          "中心性受边界、连接定义、时间段、方向、权重及流动假设限制。高分不证明领导力、质量、受欢迎程度或因果影响，低分也不证明缺乏参与。定性与时间证据可检查结构解释是否符合情境。",
        ],
        coreIdeas: [
          "不同中心性把不同种类的结构机会形式化。",
          "权重与方向必须转换至符合指标的路径逻辑。",
          "中心性排列被测量网络中的位置，而不是人的价值或因果影响。",
        ],
        practiceTask:
          "在一个五节点有向网络中，找出一个高入度节点及另一个高中介节点。解释两个分数对建议交流可能有何意义，以及各自一个可能失效的原因。",
        responsibleUse:
          "中心性排名可能变成有害的地位标签。只在必要时分享可识别分数，避免自动奖励或干预决策，呈现不确定性及边界敏感度，并邀请参与者说明网络未能观察的角色。",
        relatedConcepts: ["入度", "中介中心性", "调和接近中心性"],
      },
    },
  },
  {
    id: "academy-002",
    sequence: 2,
    slug: "build-edge-list-and-adjacency-matrix",
    track: "methods-visualization",
    level: "foundation",
    analysisApproach: "social-network-analysis",
    publishedAt: "2026-08-09",
    reviewedAt: "2026-08-09",
    durationMinutes: 10,
    sources: [
      {
        label: "Butts: Social Network Analysis with sna",
        url: "https://doi.org/10.18637/jss.v024.i06",
      },
      {
        label: "Wasserman and Faust: Social Network Analysis",
        url: "https://doi.org/10.1017/CBO9780511815478",
      },
    ],
    localizations: {
      en: {
        title: "Build an Edge List and Adjacency Matrix",
        shortSummary:
          "Turn relational records into two equivalent network representations while preserving identifiers, direction, weights, loops, and missing-data meaning.",
        tags: ["edge list", "adjacency matrix", "data quality"],
        visualLabel: "MATRIX",
        learningObjectives: [
          "Create a validated node table and edge list from relational records.",
          "Convert the edge list into an adjacency matrix without changing tie meaning.",
          "Document duplicates, loops, weights, isolates, and missing dyads before analysis.",
        ],
        scenario:
          "A learning program exports one row for every peer-feedback event. The analysis needs a clean network in which all eligible participants remain visible, including people who sent or received no recorded feedback.",
        nodes: "All participants enrolled for the complete observation window, stored once in a node table with stable pseudonymous IDs.",
        ties: "A directed weighted tie from A to B counts qualifying feedback events sent by A to B during the window.",
        networkType: "One-mode, directed, weighted event network with loops disallowed and isolates retained.",
        tutorialSteps: [
          {
            title: "Validate the node table",
            action:
              "Create one row per eligible actor with a unique stable identifier. Check duplicates, blank identifiers, ineligible records, and actors appearing in the event file but not the node table. Keep isolates in the node table.",
            checkpoint: "Every source and target ID resolves to exactly one node, and the final boundary count is recorded.",
          },
          {
            title: "Construct the edge list",
            action:
              "Select events that meet the tie rule, then group identical source-target pairs when weights represent frequency. Decide whether repeated events are counts, separate temporal events, or a binary tie, and do not mix those meanings.",
            checkpoint: "Each row has source, target, weight, and observation window, with no unexpected loops or negative counts.",
          },
          {
            title: "Create the matrix",
            action:
              "Use one documented node order for rows and columns. Place the A-to-B weight in row A, column B, keep structural zeros distinct from missing dyads, and verify the diagonal rule. Save the ordering beside the matrix.",
            checkpoint: "For N nodes, the matrix is N by N with N squared cells, and the sum of matrix weights matches the edge-list total.",
          },
          {
            title: "Run representation checks",
            action:
              "Convert the matrix back to an edge list and compare it with the validated input. Record node count, unique dyad count, total weight, isolates, loops, reciprocity candidates, and missing-dyad count in a small manifest.",
            checkpoint: "A round trip preserves every intended nonzero tie and makes every exclusion or transformation auditable.",
          },
        ],
        interpretation: [
          "An edge list is compact and convenient for recording observed ties, while an adjacency matrix makes all possible dyads explicit. They represent the same network only when they share the same node boundary, row and column order, direction, weight rule, loop rule, and missing-data convention.",
          "A zero should mean an observed absence under the study design, not that the researcher lacks information. Isolates disappear if the network is built only from the edge list, so a separate node table is necessary whenever the bounded population includes people with no recorded ties.",
        ],
        coreIdeas: [
          "The node table defines who can appear even when an actor has no observed ties.",
          "Row and column order is data and must travel with an adjacency matrix.",
          "Round-trip checks reveal lost direction, duplicated weights, and hidden missingness.",
        ],
        practiceTask:
          "Create a four-node table with one designated isolate, plus a directed edge list containing one reciprocal pair and one tie with weight 2. Convert them into a 4 by 4 matrix, then verify weight totals and the diagonal.",
        responsibleUse:
          "Use pseudonymous identifiers and keep the re-identification key outside the analysis files. Do not retain message content or unrelated personal attributes simply because the export contains them. Network structure itself can reveal identity, so access controls still matter after names are removed.",
        relatedConcepts: ["node table", "structural zero", "two-mode data"],
      },
      "zh-hant": {
        title: "建立邊列表與鄰接矩陣",
        shortSummary:
          "把關係記錄轉化為兩種等價網絡表示，同時保留識別碼、方向、權重、自連結及缺失資料的意義。",
        tags: ["邊列表", "鄰接矩陣", "資料品質"],
        visualLabel: "矩陣",
        learningObjectives: [
          "從關係記錄建立已驗證的節點表及邊列表。",
          "把邊列表轉換成鄰接矩陣而不改變連結意義。",
          "在分析前記錄重複、自連結、權重、孤立節點及缺失二元關係。",
        ],
        scenario:
          "一個學習計劃為每次同儕回饋輸出一行記錄。分析需要建立乾淨網絡，並保留所有符合資格的參與者，包括沒有送出或收到回饋的人。",
        nodes: "整個觀察時段內所有符合資格的參與者，以穩定化名識別碼各自在節點表出現一次。",
        ties: "由 A 指向 B 的有向加權連結，計算觀察時段內 A 向 B 發出的合資格回饋事件。",
        networkType: "單模式、有向、加權事件網絡，不允許自連結並保留孤立節點。",
        tutorialSteps: [
          {
            title: "驗證節點表",
            action:
              "為每位符合資格的行動者建立一行及唯一穩定識別碼。檢查重複、空白識別碼、不合資格記錄，以及事件檔案出現但節點表沒有的人。孤立節點仍應保留。",
            checkpoint: "每個來源及目標識別碼都只對應一個節點，並已記錄最終邊界人數。",
          },
          {
            title: "建立邊列表",
            action:
              "選出符合連結規則的事件，若權重代表頻率便合併相同來源及目標配對。決定重複事件是次數、獨立時間事件還是二元連結，並避免混合不同意義。",
            checkpoint: "每行都有來源、目標、權重及觀察時段，沒有意外自連結或負數次數。",
          },
          {
            title: "建立矩陣",
            action:
              "為行列採用同一個有記錄的節點次序。把 A 至 B 的權重放在 A 行 B 列，區分結構零與缺失二元關係，並核對對角線規則。把排序與矩陣一起保存。",
            checkpoint: "有 N 個節點時，矩陣為 N 乘 N，合共 N 平方個儲存格，而且矩陣權重總和與邊列表一致。",
          },
          {
            title: "執行表示檢查",
            action:
              "把矩陣轉回邊列表並與已驗證輸入比較。在小型清單記錄節點數、獨特二元關係數、總權重、孤立節點、自連結、可能互惠及缺失二元關係數。",
            checkpoint: "往返轉換保留所有預期非零連結，並讓每項排除或轉換都可審核。",
          },
        ],
        interpretation: [
          "邊列表較精簡，適合記錄觀察到的連結；鄰接矩陣則明確列出所有可能二元關係。只有當兩者共享相同節點邊界、行列次序、方向、權重規則、自連結規則及缺失資料慣例時，才代表同一網絡。",
          "零應代表研究設計下觀察到沒有連結，而不是研究者缺乏資料。若只依邊列表建立網絡，孤立節點會消失，因此當有邊界母群包含沒有連結的人時，必須另設節點表。",
        ],
        coreIdeas: [
          "節點表界定誰可以出現，包括沒有觀察到連結的人。",
          "行列次序屬於資料，必須與鄰接矩陣一同保存。",
          "往返檢查可發現方向遺失、權重重複及隱藏缺失。",
        ],
        practiceTask:
          "建立一個四節點表，指定其中一個為孤立節點；另建立有向邊列表，包含一對互惠連結及一條權重為 2 的連結。把兩者轉成 4 乘 4 矩陣，並核對權重總和與對角線。",
        responsibleUse:
          "使用化名識別碼，並把重新識別對照表存放於分析檔案以外。不要只因輸出包含訊息內容或無關個人屬性便予以保留。網絡結構本身也可能揭示身分，因此移除姓名後仍需要存取控制。",
        relatedConcepts: ["節點表", "結構零", "二模資料"],
      },
      "zh-hans": {
        title: "建立边列表与邻接矩阵",
        shortSummary:
          "把关系记录转化为两种等价网络表示，同时保留标识符、方向、权重、自连接及缺失数据的意义。",
        tags: ["边列表", "邻接矩阵", "数据质量"],
        visualLabel: "矩阵",
        learningObjectives: [
          "从关系记录建立已验证的节点表及边列表。",
          "把边列表转换成邻接矩阵而不改变连接意义。",
          "在分析前记录重复、自连接、权重、孤立节点及缺失二元关系。",
        ],
        scenario:
          "一个学习计划为每次同伴反馈输出一行记录。分析需要建立干净网络，并保留所有符合资格的参与者，包括没有发出或收到反馈的人。",
        nodes: "整个观察时间段内所有符合资格的参与者，以稳定化名标识符各自在节点表出现一次。",
        ties: "由 A 指向 B 的有向加权连接，计算观察时间段内 A 向 B 发出的合资格反馈事件。",
        networkType: "单模式、有向、加权事件网络，不允许自连接并保留孤立节点。",
        tutorialSteps: [
          {
            title: "验证节点表",
            action:
              "为每位符合资格的行动者建立一行及唯一稳定标识符。检查重复、空白标识符、不合资格记录，以及事件文件出现但节点表没有的人。孤立节点仍应保留。",
            checkpoint: "每个来源及目标标识符都只对应一个节点，并已记录最终边界人数。",
          },
          {
            title: "建立边列表",
            action:
              "选出符合连接规则的事件，若权重代表频率便合并相同来源及目标配对。决定重复事件是次数、独立时间事件还是二元连接，并避免混合不同意义。",
            checkpoint: "每行都有来源、目标、权重及观察时间段，没有意外自连接或负数次数。",
          },
          {
            title: "建立矩阵",
            action:
              "为行列采用同一个有记录的节点次序。把 A 至 B 的权重放在 A 行 B 列，区分结构零与缺失二元关系，并核对对角线规则。把排序与矩阵一起保存。",
            checkpoint: "有 N 个节点时，矩阵为 N 乘 N，共有 N 平方个单元格，而且矩阵权重总和与边列表一致。",
          },
          {
            title: "执行表示检查",
            action:
              "把矩阵转回边列表并与已验证输入比较。在小型清单记录节点数、独特二元关系数、总权重、孤立节点、自连接、可能互惠及缺失二元关系数。",
            checkpoint: "往返转换保留所有预期非零连接，并让每项排除或转换都可审核。",
          },
        ],
        interpretation: [
          "边列表较精简，适合记录观察到的连接；邻接矩阵则明确列出所有可能二元关系。只有当两者共享相同节点边界、行列次序、方向、权重规则、自连接规则及缺失数据惯例时，才代表同一网络。",
          "零应代表研究设计下观察到没有连接，而不是研究者缺乏数据。若只按边列表建立网络，孤立节点会消失，因此当有边界总体包含没有连接的人时，必须另设节点表。",
        ],
        coreIdeas: [
          "节点表界定谁可以出现，包括没有观察到连接的人。",
          "行列次序属于数据，必须与邻接矩阵一同保存。",
          "往返检查可发现方向遗失、权重重复及隐藏缺失。",
        ],
        practiceTask:
          "建立一个四节点表，指定其中一个为孤立节点；另建立有向边列表，包含一对互惠连接及一条权重为 2 的连接。把两者转成 4 乘 4 矩阵，并核对权重总和与对角线。",
        responsibleUse:
          "使用化名标识符，并把重新识别对照表存放于分析文件以外。不要只因输出包含消息内容或无关个人属性便予以保留。网络结构本身也可能揭示身份，因此移除姓名后仍需要访问控制。",
        relatedConcepts: ["节点表", "结构零", "二模数据"],
      },
    },
  },
  {
    id: "academy-001",
    sequence: 1,
    slug: "define-nodes-ties-and-boundaries",
    track: "network-theory",
    level: "foundation",
    analysisApproach: "social-network-analysis",
    publishedAt: "2026-08-09",
    reviewedAt: "2026-08-09",
    durationMinutes: 9,
    sources: [
      {
        label: "Wasserman and Faust: Social Network Analysis",
        url: "https://doi.org/10.1017/CBO9780511815478",
      },
      {
        label: "Borgatti and colleagues: Network analysis in the social sciences",
        url: "https://doi.org/10.1126/science.1165821",
      },
    ],
    localizations: {
      en: {
        title: "Define Nodes, Ties, and Boundaries Before Analysis",
        shortSummary:
          "Translate a relational question into an explicit network design by defining who can be a node, what counts as a tie, and where observation begins and ends.",
        tags: ["nodes", "ties", "network boundary"],
        visualLabel: "BOUNDARY",
        learningObjectives: [
          "Distinguish a relational question from a question about individual attributes alone.",
          "Write operational definitions for nodes, ties, direction, weight, boundary, and time window.",
          "Separate an observed absence of a tie from missing or unobserved relational data.",
        ],
        scenario:
          "A course team asks how students seek help while completing a group project. Before calculating a metric, the team must decide whether the network represents advice, friendship, messages, co-membership, or another relationship, because each choice creates a different network.",
        nodes: "Students officially enrolled in the project course for the full four-week observation window.",
        ties: "A directed tie from A to B means A reported seeking substantive project advice from B at least once during the window.",
        networkType: "One-mode, directed, binary advice network with loops disallowed and all eligible students retained.",
        tutorialSteps: [
          {
            title: "Start with a relational question",
            action:
              "Write a question whose answer depends on connections, such as who seeks advice from whom or how separate groups exchange knowledge. If the question can be answered from one row per person without relationships, SNA may not be the needed approach.",
            checkpoint: "The question names a relationship and a structural pattern, not only an individual outcome.",
          },
          {
            title: "Define the nodes and boundary",
            action:
              "State the unit represented by each node and the rule for inclusion. Use roster, event, positional, or another defensible boundary rule, and specify the dates during which actors and ties were eligible to be observed.",
            checkpoint: "Another analyst could reproduce the node set from the written inclusion rule without asking whom you intended to include.",
          },
          {
            title: "Operationalize the tie",
            action:
              "Describe the event or report that creates a tie, its direction, whether it is binary or weighted, whether loops are possible, and how repeated events are combined. Avoid treating platform proximity as a social relation without justification.",
            checkpoint: "A raw record can be classified consistently as a tie, a non-tie, or missing under the rule.",
          },
          {
            title: "Write the network specification",
            action:
              "Record the research question, node rule, tie rule, boundary, observation window, direction, weight, loop rule, missing-data rule, and intended analysis. Add one sentence describing what the network cannot observe.",
            checkpoint: "The specification is complete before visualization or metric selection begins.",
          },
        ],
        interpretation: [
          "The network is not discovered automatically in raw data. It is constructed through defensible measurement choices. A roster boundary answers a different question from an event-based boundary, and an advice nomination answers a different question from a message count or shared group membership.",
          "Every later measure inherits these choices. Centrality, density, communities, and models cannot repair a vague tie definition or an incomplete boundary. Sensitivity analysis can compare plausible specifications, but the original question and data-generating process must guide which version receives the primary interpretation.",
        ],
        coreIdeas: [
          "SNA begins with a relational question and an explicit network specification.",
          "Nodes, ties, direction, weights, boundaries, and time windows are measurement choices.",
          "A missing tie observation is not the same as an observed absence of a tie.",
        ],
        practiceTask:
          "For an eight-person project team, write one advice-network specification and one co-participation-network specification. Explain why they would support different claims even if both use the same people.",
        responsibleUse:
          "Collect only relationships needed for the stated purpose. Tell participants what a nomination means, who can access raw ties, how long records remain, and which decisions will not be made from the network. Pseudonyms reduce direct identification but do not make a distinctive network anonymous.",
        relatedConcepts: ["relational question", "boundary specification", "missing ties"],
      },
      "zh-hant": {
        title: "分析前先界定節點、連結與邊界",
        shortSummary:
          "把關係研究問題轉化為明確網絡設計，界定誰可以成為節點、甚麼算作連結，以及觀察從何處開始與結束。",
        tags: ["節點", "連結", "網絡邊界"],
        visualLabel: "邊界",
        learningObjectives: [
          "區分關係研究問題與只關注個人屬性的問題。",
          "為節點、連結、方向、權重、邊界及時段寫出操作定義。",
          "區分觀察到沒有連結與缺失或未被觀察的關係資料。",
        ],
        scenario:
          "課程團隊希望了解學生完成小組專題時如何尋求協助。在計算指標前，團隊必須決定網絡代表建議、友誼、訊息、共同成員身分或其他關係，因為每個選擇都會建立不同網絡。",
        nodes: "在完整四週觀察時段正式修讀專題課程的學生。",
        ties: "由 A 指向 B 的有向連結，表示 A 報告在觀察時段至少一次向 B 尋求實質專題建議。",
        networkType: "單模式、有向、二元建議網絡，不允許自連結並保留所有符合資格的學生。",
        tutorialSteps: [
          {
            title: "由關係問題開始",
            action:
              "寫出答案取決於連結的問題，例如誰向誰尋求建議，或分離群組如何交換知識。若問題只需每人一行屬性資料便可回答，SNA 可能不是所需方法。",
            checkpoint: "問題指出一種關係及一個結構模式，而不只是個人結果。",
          },
          {
            title: "界定節點與邊界",
            action:
              "說明每個節點代表的單位及納入規則。採用名冊、事件、位置或其他可辯護的邊界規則，並指定行動者及連結有資格被觀察的日期。",
            checkpoint: "另一位分析者只依書面納入規則便能重現節點集合。",
          },
          {
            title: "操作化連結",
            action:
              "描述建立連結的事件或報告、方向、二元或加權設定、自連結是否可能，以及重複事件如何合併。沒有充分理由時，不要把平台上的接近直接當作社會關係。",
            checkpoint: "原始記錄可按規則一致分類為連結、沒有連結或缺失。",
          },
          {
            title: "寫出網絡規格",
            action:
              "記錄研究問題、節點規則、連結規則、邊界、觀察時段、方向、權重、自連結規則、缺失資料規則及預定分析。再加入一句說明網絡無法觀察甚麼。",
            checkpoint: "在開始視覺化或選擇指標前，網絡規格已完整。",
          },
        ],
        interpretation: [
          "網絡不是由原始資料自動發現，而是透過可辯護的量度選擇建構。名冊邊界與事件邊界回答不同問題，建議提名與訊息次數或共同群組身分也代表不同關係。",
          "所有後續指標都承接這些選擇。中心性、密度、社群及模型不能修補含糊連結定義或不完整邊界。敏感度分析可比較合理規格，但主要詮釋仍應由原始問題及資料生成過程引導。",
        ],
        coreIdeas: [
          "SNA 由關係問題及明確網絡規格開始。",
          "節點、連結、方向、權重、邊界及時段都是量度選擇。",
          "缺失的連結觀察不等同於觀察到沒有連結。",
        ],
        practiceTask:
          "為八人專題團隊分別寫出一個建議網絡及共同參與網絡規格。解釋為何即使兩者使用相同人物，也支持不同主張。",
        responsibleUse:
          "只收集符合既定目的的關係。向參與者說明提名的意義、誰可存取原始連結、資料保留多久，以及哪些決定不會根據網絡作出。化名可減少直接識別，但不能令具獨特結構的網絡完全匿名。",
        relatedConcepts: ["關係問題", "邊界規格", "缺失連結"],
      },
      "zh-hans": {
        title: "分析前先界定节点、连接与边界",
        shortSummary:
          "把关系研究问题转化为明确网络设计，界定谁可以成为节点、什么算作连接，以及观察从何处开始与结束。",
        tags: ["节点", "连接", "网络边界"],
        visualLabel: "边界",
        learningObjectives: [
          "区分关系研究问题与只关注个人属性的问题。",
          "为节点、连接、方向、权重、边界及时间段写出操作定义。",
          "区分观察到没有连接与缺失或未被观察的关系数据。",
        ],
        scenario:
          "课程团队希望了解学生完成小组项目时如何寻求帮助。在计算指标前，团队必须决定网络代表建议、友谊、消息、共同成员身份或其他关系，因为每个选择都会建立不同网络。",
        nodes: "在完整四周观察时间段正式修读项目课程的学生。",
        ties: "由 A 指向 B 的有向连接，表示 A 报告在观察时间段至少一次向 B 寻求实质项目建议。",
        networkType: "单模式、有向、二元建议网络，不允许自连接并保留所有符合资格的学生。",
        tutorialSteps: [
          {
            title: "从关系问题开始",
            action:
              "写出答案取决于连接的问题，例如谁向谁寻求建议，或分离群组如何交换知识。若问题只需每人一行属性数据便可回答，SNA 可能不是所需方法。",
            checkpoint: "问题指出一种关系及一个结构模式，而不只是个人结果。",
          },
          {
            title: "界定节点与边界",
            action:
              "说明每个节点代表的单位及纳入规则。采用名册、事件、位置或其他可辩护的边界规则，并指定行动者及连接有资格被观察的日期。",
            checkpoint: "另一位分析者只按书面纳入规则便能重现节点集合。",
          },
          {
            title: "操作化连接",
            action:
              "描述建立连接的事件或报告、方向、二元或加权设定、自连接是否可能，以及重复事件如何合并。没有充分理由时，不要把平台上的接近直接当作社会关系。",
            checkpoint: "原始记录可按规则一致分类为连接、没有连接或缺失。",
          },
          {
            title: "写出网络规格",
            action:
              "记录研究问题、节点规则、连接规则、边界、观察时间段、方向、权重、自连接规则、缺失数据规则及预定分析。再加入一句说明网络无法观察什么。",
            checkpoint: "在开始可视化或选择指标前，网络规格已完整。",
          },
        ],
        interpretation: [
          "网络不是由原始数据自动发现，而是通过可辩护的测量选择建构。名册边界与事件边界回答不同问题，建议提名与消息次数或共同群组身份也代表不同关系。",
          "所有后续指标都承接这些选择。中心性、密度、社群及模型不能修补含糊连接定义或不完整边界。敏感度分析可比较合理规格，但主要解释仍应由原始问题及数据生成过程引导。",
        ],
        coreIdeas: [
          "SNA 从关系问题及明确网络规格开始。",
          "节点、连接、方向、权重、边界及时间段都是测量选择。",
          "缺失的连接观察不等同于观察到没有连接。",
        ],
        practiceTask:
          "为八人项目团队分别写出一个建议网络及共同参与网络规格。解释为何即使两者使用相同人物，也支持不同主张。",
        responsibleUse:
          "只收集符合既定目的的关系。向参与者说明提名的意义、谁可访问原始连接、数据保留多久，以及哪些决定不会根据网络作出。化名可减少直接识别，但不能让具独特结构的网络完全匿名。",
        relatedConcepts: ["关系问题", "边界规格", "缺失连接"],
      },
    },
  },
];

export function localizeAcademyLesson(
  lesson: AcademyLessonRecord,
  locale: Locale,
): LocalizedAcademyLesson {
  const { localizations, ...shared } = lesson;
  return { ...shared, ...localizations[locale] };
}

export function getAcademyLesson(slug: string) {
  return academyLessons.find((lesson) => lesson.slug === slug);
}

export function getRelatedAcademyLessons(
  lesson: AcademyLessonRecord,
  locale: Locale,
  limit = 3,
): LocalizedAcademyLesson[] {
  const tags = new Set(lesson.localizations.en.tags.map((tag) => tag.toLowerCase()));

  return academyLessons
    .filter((candidate) => candidate.id !== lesson.id)
    .map((candidate) => ({
      candidate,
      score:
        candidate.localizations.en.tags.filter((tag) => tags.has(tag.toLowerCase())).length * 3 +
        Number(candidate.track === lesson.track) * 2 +
        Number(candidate.level === lesson.level) -
        Math.abs(candidate.sequence - lesson.sequence) * 0.01,
    }))
    .sort((left, right) => right.score - left.score || right.candidate.sequence - left.candidate.sequence)
    .slice(0, Math.max(0, Math.floor(limit)))
    .map(({ candidate }) => localizeAcademyLesson(candidate, locale));
}

export function getAcademySequenceNeighbors(lesson: AcademyLessonRecord, locale: Locale) {
  const ordered = [...academyLessons].sort((left, right) => left.sequence - right.sequence);
  const index = ordered.findIndex((candidate) => candidate.id === lesson.id);

  return {
    previous: index > 0 ? localizeAcademyLesson(ordered[index - 1], locale) : undefined,
    next: index >= 0 && index < ordered.length - 1
      ? localizeAcademyLesson(ordered[index + 1], locale)
      : undefined,
  };
}

export const academyTracks = ACADEMY_TRACKS;
export const academyLevels = ACADEMY_LEVELS;
